#!/usr/bin/env bash

#MISE description="Setup AI plugins"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

# print_header "Adding marketplaces ..."
# pnpx @askviraj/ai-plugins --all
